const data = [
    { chosung: 'ㄴㄴ ㄴㅁ ㅇㅃ', hint: '그 그녀를 보는 나는 미쳐 하 하지만 이젠 지쳐', answer: '누난 너무 예뻐' },
    { chosung: 'ㅇ ㅁㅇ ㄹ', hint: 'Cause you were my sun, the moon 내 전부 였던 너', answer: '인 마이 룸' },
    { chosung: 'ㄹㅇ', hint: '너를 가두고 있던 지루한 old fashion 이제는 벗어버리고 너다운 solution', answer: '리얼' },
    { chosung: 'ㅅ.ㄱ.ㅎ', hint: 'Love forever and last forever 온 내 맘 다해도 잡히지도 늦출 수도 없는 널', answer: '사.계.한' },
    { chosung: 'ㄴㄱ ㅁㅇ ㄷㅇ', hint: '난 니가 맘에 너무 들었어 정말 그것뿐인 걸', answer: '니가 맘에 들어' },
    { chosung: 'ㅈㄹㅇ', hint: 'ㅈㄹㅇ! 호~ 영혼을 바칠게요 ㅈㄹㅇ! 호~ 제발 날 받아 줘요', answer: '줄리엣' },
    { chosung: 'ㅊㄹㄹ ㄸㄹ', hint: '삐쳐있지 말고 차라리 날 때려줘 난 그렇게라도 기분 풀렸음 좋겠어', answer: '차라리 때려' },
    { chosung: 'ㅅㄴㄹㄸ', hint: '거짓말처럼 반해버렸다 아 바보같이. 너만 가득 찬 내 눈동자엔 Zoom', answer: '세뇨리따' },
    { chosung: '잠꼬대', hint: '안돼요 안돼요 그렇게 가지마요 제발 한 번만 한 번만 날 다시 안아줘요', answer: '잠꼬대' },
    { chosung: 'ㅅㄴ, ㅅㄴㄹ ㅁㄴㄷ', hint: '그 사랑이 또 시작돼 그대를 사랑한 나의 맘조차 날 알지 못하고', answer: '소년, 소녀를 만나다' },
    { chosung: 'ㅇ', hint: 'Nothing can stop me from loving you you you', answer: '유' },
    { chosung: 'ㄹㄷㄷ', hint: 'Baby 네게 반해버린 내게 왜 이래 두렵다고 물러서지 말고 그냥 내게 맡겨봐라 어때 My lady', answer: '링딩동' },
    { chosung: 'ㅈㅈ', hint: 'ㅈㅈ! 슬픈 음악이 흐를 때 널 생각해 (eh eh eh)', answer: '조조' },
    { chosung: 'ㄱ ㄷㅇ', hint: 'Get Down 나나나 나나나 나나나', answer: '겟 다운' },
    { chosung: 'ㅅㅇㄴ ㄱ', hint: '나만의 상상 둘이 la la like Happy day 단둘이 luv luv luv Sunny day', answer: '샤이니 걸' },
    { chosung: 'ㄴㄱ ㅅㄹㅎㄷ ㅇㄹ', hint: '내가 사랑했던 그 이름 불러보려 나갈수록 너무 멀어졌던', answer: '내가 사랑했던 이름' },
    { chosung: 'ㅅㄹ', hint: 'SHINee’s Back', answer: '셜록' },
    { chosung: 'ㅋㄹ', hint: '범인은 이 안에 있어 아무도 나갈 수 없어 너와 나 어떤 누구도', answer: '클루' },
    { chosung: 'ㄴㅌ', hint: 'Oh I’m curious yea 사진 속 네가 순간 미소지어 왜', answer: '노트' },
    { chosung: 'ㅇㄹㅅㄱ', hint: '나의 알람시계가 어서 울려 이 꿈을 깨버리길', answer: '알람시계' },
    { chosung: 'ㄷ ㄹㅈ', hint: '너와 함께 했던 많은 시간들이 모르고 지낸 행복했던 순간들이', answer: '더 리즌' },
    { chosung: 'ㄴㅅㅈ', hint: 'Can’t get you out of my head 널 원해 천 번을 생각해봐도 그래', answer: '낯선자' },
    { chosung: 'ㄴ ㄱ ㅈㄹㅇㅅ', hint: '늘 그 자리에 있어 날 지켜줘서 늘 내가 받을 비난 대신해서', answer: '늘 그 자리에서' },
    { chosung: 'ㅇㅂㄹㅂㄷ', hint: 'Wow ㅇㅂㄹㅂㄷ Wake up Wake up', answer: '에브리바디' },
    { chosung: 'ㅅㅅㅂ', hint: '날 휘감은 너란 병이 깊어 갈수록 더 지쳐 약은 너밖에 없어', answer: '상사병' },
    { chosung: 'ㅂ ㅅ ㄴㅇ', hint: '아무 생각 없이 간 그 거리 골목 사랑은 타이밍 그래 뉴욕', answer: '빗 속 뉴욕' },
    { chosung: 'ㅇㅂㅁ(숫자 있음)', hint: '1분만 더 1분만 더 시간아 시간을 뒤로 돌려', answer: '1분만' },
    { chosung: 'ㄷㅅㅌㄴㅇㅅ', hint: '깃발이 바람에 휘날려 내 눈 앞은 어둡게 가려져 난 볼 수 있을까', answer: '데스티네이션' },
    { chosung: 'ㄷㅇㅈ', hint: '그 말을 생각하면 지금 널 이해 할 수 없어', answer: '닫아줘' },
    { chosung: 'ㅋㄹㅍ', hint: '내가 잘 못 본 걸까 너의 손이 닿는 순간 내 주변 모든 것이 물들어', answer: '컬러풀' },
    
  ];
  
  export default data;
  