const data = [
    { chosung: 'ㄴㄴ ㄴㅁ ㅇㅃ', hint: '그 그녀를 보는 나는 미쳐 하 하지만 이젠 지쳐', answer: '누난 너무 예뻐' },
    { chosung: 'ㅇ ㅁㅇ ㄹ', hint: 'Cause you were my sun, the moon 내 전부 였던 너', answer: '인 마이 룸' },
    { chosung: 'ㄹㅇ', hint: '너를 가두고 있던 지루한 old fashion 이제는 벗어버리고 너다운 solution', answer: '리얼' },
    { chosung: 'ㅅ.ㄱ.ㅎ(ㅅㄹㅇ ㄱㅅㄷㅇㅇㅎㄷ)', hint: 'Love forever and last forever 온 내 맘 다해도 잡히지도 늦출 수도 없는 널', answer: '사.계.한(사랑은 계속되어야한다)' },
    { chosung: 'ㄴㄱ ㅁㅇ ㄷㅇ', hint: '난 니가 맘에 너무 들었어 정말 그것뿐인 걸', answer: '니가 맘에 들어' },
    { chosung: 'ㅈㄹㅇ', hint: 'ㅈㄹㅇ! 호~ 영혼을 바칠게요 ㅈㄹㅇ! 호~ 제발 날 받아 줘요', answer: '줄리엣' },
    { chosung: 'ㅊㄹㄹ ㄸㄹ', hint: '삐쳐있지 말고 차라리 날 때려줘 난 그렇게라도 기분 풀렸음 좋겠어', answer: '차라리 때려' },
    { chosung: 'ㅅㄴㄹㄸ', hint: '거짓말처럼 반해버렸다 아 바보같이. 너만 가득 찬 내 눈동자엔 Zoom', answer: '세뇨리따' },
    { chosung: 'ㅈㄲㄷ', hint: '안돼요 안돼요 그렇게 가지마요 제발 한 번만 한 번만 날 다시 안아줘요', answer: '잠꼬대' },
    { chosung: 'ㅅㄴ, ㅅㄴㄹ ㅁㄴㄷ', hint: '그 사랑이 또 시작돼 그대를 사랑한 나의 맘조차 날 알지 못하고', answer: '소년, 소녀를 만나다' },
    { chosung: 'ㅇ', hint: 'Nothing can stop me from loving you you you', answer: '유' },
    { chosung: 'ㄹㄷㄷ', hint: 'Baby 네게 반해버린 내게 왜 이래 두렵다고 물러서지 말고 그냥 내게 맡겨봐라 어때 My lady', answer: '링딩동' },
    { chosung: 'ㅈㅈ', hint: 'ㅈㅈ! 슬픈 음악이 흐를 때 널 생각해 (eh eh eh)', answer: '조조' },
    { chosung: 'ㄱ ㄷㅇ', hint: 'Get Down 나나나 나나나 나나나', answer: '겟 다운' },
    { chosung: 'ㅅㅇㄴ ㄱ', hint: '나만의 상상 둘이 la la like Happy day 단둘이 luv luv luv Sunny day', answer: '샤이니 걸' },
    { chosung: 'ㄴㄱ ㅅㄹㅎㄷ ㅇㄹ', hint: '내가 사랑했던 그 이름 불러보려 나갈수록 너무 멀어졌던', answer: '내가 사랑했던 이름' },
    { chosung: 'ㅅㄹ', hint: 'SHINee’s Back', answer: '셜록' },
    { chosung: 'ㅋㄹ', hint: '범인은 이 안에 있어 아무도 나갈 수 없어 너와 나 어떤 누구도', answer: '클루' },
    { chosung: 'ㄴㅌ', hint: 'Oh I’m curious yea 사진 속 네가 순간 미소지어 왜', answer: '노트' },
    { chosung: 'ㅇㄹㅅㄱ', hint: '나의 알람시계가 어서 울려 이 꿈을 깨버리길', answer: '알람시계' },
    { chosung: 'ㄷ ㄹㅈ', hint: '너와 함께 했던 많은 시간들이 모르고 지낸 행복했던 순간들이', answer: '더 리즌' },
    { chosung: 'ㄴㅅㅈ', hint: 'Can’t get you out of my head 널 원해 천 번을 생각해봐도 그래', answer: '낯선자' },
    { chosung: 'ㄴ ㄱ ㅈㄹㅇㅅ', hint: '늘 그 자리에 있어 날 지켜줘서 늘 내가 받을 비난 대신해서', answer: '늘 그 자리에서' },
    { chosung: 'ㅇㅂㄹㅂㄷ', hint: 'Wow ㅇㅂㄹㅂㄷ Wake up Wake up', answer: '에브리바디' },
    { chosung: 'ㅅㅅㅂ', hint: '날 휘감은 너란 병이 깊어 갈수록 더 지쳐 약은 너밖에 없어', answer: '상사병' },
    { chosung: 'ㅂ ㅅ ㄴㅇ', hint: '아무 생각 없이 간 그 거리 골목 사랑은 타이밍 그래 뉴욕', answer: '빗 속 뉴욕' },
    { chosung: 'ㅇㅂㅁ(숫자 있음)', hint: '1분만 더 1분만 더 시간아 시간을 뒤로 돌려', answer: '1분만' },
    { chosung: 'ㄷㅅㅌㄴㅇㅅ', hint: '깃발이 바람에 휘날려 내 눈 앞은 어둡게 가려져 난 볼 수 있을까', answer: '데스티네이션' },
    { chosung: 'ㄷㅇㅈ', hint: '그 말을 생각하면 지금 널 이해 할 수 없어', answer: '닫아줘' },
    { chosung: 'ㅋㄹㅍ', hint: '내가 잘 못 본 걸까 너의 손이 닿는 순간 내 주변 모든 것이 물들어', answer: '컬러풀' },
    { chosung: 'ㄷ ㅅㅇㄴ ㅇㄷ', hint: '블링블링 is 종현 우리 박력탬은 태민 두부 온리다는 온유 SHINee 만능열쇠 Key 불꽃 카리스마 민호', answer: '더 샤이니 월드' },
    { chosung: 'ㅅㄹㅇ ㄱ', hint: '수백 번 다투고 백번 가슴 무너져도 실들이 엉킨 듯, 떼낼 수 없는 사랑', answer: '사랑의 길' },
    { chosung: 'ㅅㅅㄱㅇ ㄴ', hint: '떨어져 깨질듯한 투명한 네게 달콤한 독물 퍼지듯', answer: '산소같은 너' },
    { chosung: 'ㄴ ㅇㄴㅁ ㅇㄷㄴ ㄱ', hint: '너 아니면 안되는 걸 이제야 알아버린 내가 너무 비참해', answer: '너 아니면 안되는 걸' },
    { chosung: 'ㄱㄴㄱ ㅎㅇㅈㄷ', hint: '그녀의 옆에 영원히 곁에 내 자릴 만들어 놓고서', answer: '그녀가 헤어졌다' },
    { chosung: 'ㅎㅈㅇ ㅎㄱ', hint: ' 스쳐간다 그 사람 손을 잡은 채 멀어져간다 조금 진한 화장을 하고', answer: '화장을 하고' },
    { chosung: 'ㅁㅈㅁ ㅅㅁ', hint: '너에게 끼워준 반지가 내 손에 차갑게 돌아와', answer: '마지막 선물' },
    { chosung: 'ㅎㅇ', hint: '혜야, 어찌 떠나려는 거야 웃는 그 눈으로 안녕이란 잔인한 말은 나를 죽이고 숨이 멈춰', answer: '혜야' },
    { chosung: 'ㄴㅇ ㄱㅇㅂㅁ', hint: 'I’ll wait for you (until the end) 기억할게 사계절에 숨어있는 니 모습 눈을 감아보면 넌 어느새 곁에 있어', answer: '눈을 감아보면' },
    { chosung: 'ㄴ ㄱㅇㅁ ㅇㅇ', hint: '내 곁에만 있어 언제나 너는 나의 Lady 내 맘은 너와 함께 Crazy', answer: '네 곁에만 있어' },
    { chosung: 'ㅇ ㅇ ㄷㅇ', hint: '너 왜 너 왜 down이야 기분이 오 왜 오 왜 척하면 척', answer: '업 앤 다운' },
    { chosung: 'ㄹㅅㅍ', hint: '나를 묶고 가둔다면 사랑도 묶인 채 미래도 묶인 채 커질 수 없는데', answer: '루시퍼' },
    { chosung: 'ㅇㄹㅌㄹ ㅎㅌ', hint: '미쳐 그런 너의 눈빛 행동 말투 도도한 건방진 니 Attitude 내 가슴은 터질듯해', answer: '일레트릭 하트' },
    { chosung: 'ㅇㅇ-ㅇ', hint: 'A Yo 힘이 들 땐 둥타닥 rhythm에 기대어 oh 널 향한 우리의 노래로 oh', answer: '에이-요' },
    { chosung: 'ㅇ', hint: '욕해 놓쳐버린 날 욕해 무너진 내 심장은 날 버리지마 날 혼자 두지마 외치고 있지만', answer: '욕' },
    { chosung: 'ㅎㅅ', hint: '오 그대 맘에 닿고 싶은 날 말하지 못해', answer: '화살' },
    { chosung: 'ㅇ', hint: '니가 듣지 못해도 I won’t give up 이제껏 뭘 느껴왔던 I won’t give up', answer: '악' },
    { chosung: 'ㅇㅇㅇㅇㅇㅇ', hint: 'WOWOWOW 느낌이 좋아 너무나 좋아', answer: '와우와우와우' },
    { chosung: 'ㅇㅇ ㄴㅇ', hint: '나를 불러줘 My name 오늘이 바로 Your day', answer: '유얼 네임' },
    { chosung: 'ㄹㅇㅍ', hint: '세상에 무릎 꿇고 눈물 흘릴 때 폭풍 속 발 멈출 때 그대만 서 있다면', answer: '라이프' },
    { chosung: 'ㄹㄷ ㅇ ㄴ', hint: 'Are you ready or not You ready or not 안될 것 같아 또 굳게 입술을 닫는다', answer: '레디 올 낫' },
    { chosung: 'ㄹㅂ ㅍㅇ', hint: '지울 수도 없어 버릴 수도 없어 또 하루를 버티고', answer: '러브 페인' },
    { chosung: 'ㅅ.ㄱ.ㅎ(ㅅㄹㅇ ㄱㅅㄷ ㅎㅇ)', hint: '사랑은 꼭 계속 돼야만 해요 다가설수록 더 멀어져', answer: '사.계.후(사랑이 계속된 후에)' },
    { chosung: 'ㅅㅍㅇㄹ', hint: '상상도 못했을 이 스포일러 깜짝 놀라긴 아직 일러', answer: '스포일러' },
    { chosung: 'ㄷㄹ ㄱ', hint: '어디서부터 시작되었는지 그게 중요한 게 아냐 지금 내 눈엔 너무 완벽한 네 모습만 보이는 걸', answer: '드림 걸' },
    { chosung: 'ㅎㅊㅎㅇㅋ', hint: '또 다른 세상의 너와 나 지친 심장을 뛰게 해 내친 꿈들을 좇게 해 Baby', answer: '히치하이킹' },
    { chosung: 'ㅍㅊ ㄷㄹㅋ ㄹㅂ', hint: 'Punch One Two 난 정신 차릴 수가 없어', answer: '펀치 드렁크 러브' },
    { chosung: 'ㄱㅅ, ㄱㅅ, ㄱㅅ', hint: 'Girls, Girls, Girls 내겐 너무 어려운 걸', answer: '걸스, 걸스, 걸스' },
    { chosung: 'ㅂㅂ', hint: '날 보며 웃을 때 마다 맘 속 갚은 곳에선 심각해지는 병이 있어요', answer: '방백' },
    { chosung: 'ㅇㄹㄷㅇ', hint: '네 상처까지도 나에게 줘', answer: '아름다워' },
    { chosung: 'ㄷㅇㄴㅁㅇㅌ', hint: '다이너마이트 마이트 차가운 너의 눈빛 나 살아갈 이율 알아버렸다', answer: '다이너마이트' },
    { chosung: 'ㄹㅇㅇㅇ', hint: '출발 목적진 없어도 너만 옆에 있다면 세상 어디든지 언제든지 Alright', answer: 'ㄹㅇㅇㅇ' },
    { chosung: 'ㄴㅇㅌㅁㅇ', hint: '내 모든 걸 앗은 뱀파이어 잡히지 않을 만큼 넌 이미 멀어져 가', answer: '나이트메어' },
    { chosung: 'ㅇㅇ ㅆ ㅅㄹㅇㅅ', hint: '로미오와 줄리엣은 슬픈 러브스토리가 아 아니야', answer: '와이 쏘 시리어스' },
    { chosung: 'ㅅㅇ', hint: 'Yeah you’re SHINin’ in the east Yeah you’re SHINin’ in the west', answer: '샤인' },
    { chosung: 'ㅇㄹㄱ', hint: '빙글빙글 돌아가네 날 위한 노래', answer: '오르골' },
    { chosung: 'ㄷㅇㅈㄹㅅ', hint: '화려할수록 더 가시가 많아 결국 잡지 못할 것을 잘 알고 있지만', answer: '데인저러스' },
    { chosung: 'ㄹㅇㅋ ㅇ ㅍㅇㅇ', hint: '모조리 태울게 나의 사랑을 Like a Fire Like a Fire', answer: '라이크 어 파이어' },
    { chosung: 'ㅇㅅㅋㅅ ㅁ ㅁㅅ', hint: 'Excuse Me Miss 바닐라 아이스 너와의 키스 꿈꿔 온 Peace', answer: '익스큐스 미 미스' },
    { chosung: 'ㅇㅂ', hint: '이슈 없다면 사라져라 더는 널 볼 일 없도록 잠들지 않을 테니', answer: '이블' },
    { chosung: 'ㄸㄴㅈ ㅁㅎ', hint: '나보다도 소중했던 널 다시 돌아와 Tonight', answer: '떠나지 못해' },
    { chosung: 'ㅇㄷㅇㅇ', hint: '결국 이곳 모든 시선 독차지 한 것도 Oh you My eyes on you', answer: '오드아이' },
    { chosung: 'ㄹㅂ ㅅ', hint: '왜지 여전히 널 보면 난 아파 사랑만 깊어져 미쳤어 I need a doctor', answer: '러브 식' },
    { chosung: 'ㅂ', hint: '모두 할말을 잃지 like you', answer: '뷰' },
    { chosung: 'ㄹㅁㅅ', hint: '이건 기적 뒤에 숨은 노력 Ah 확실한 건 우리는 운명', answer: '로맨스' },
    { chosung: 'ㅌㄹㄱ', hint: '시작해 자 Shoot the gun 이 악몽은 곧 끝나', answer: '트리거' },
    { chosung: 'ㅇㅂㅇ ㄱ', hint: '사랑을 숨길 수가 없듯이 다 느껴지는 이별도 숨길 수가 없잖아 더 아프니까', answer: '이별의 길' },
    { chosung: 'ㄴㅇ ㄴㄹㄱ ㄷㅇ', hint: '너의 노래가 되어 잔잔한 음악이 되어 너의 아픈 눈물 모두 닦아줄 수가 있도록', answer: '너의 노래가 되어' },
    { chosung: 'ㅇㄹㅇㅂ', hint: '네가 빛날 때 세상이 비로소 움직여 살아 움직여 그 푸른빛이 빛날 때', answer: '어라이브' },
    { chosung: 'ㅇㅍㅇㅍ', hint: '내가 따라가도 피하면 안 돼 꼬리를 계속 흔들어 멈출 수 없어', answer: '우프우프' },
    { chosung: 'ㅂㄹㅎ', hint: '너는 내 Black Hole Woo 벗어날 수가 없는 끌림인 걸 Oh 그런 끌림인 걸 Oh', answer: '블랙홀' },
    { chosung: 'ㅈㅇ', hint: '익숙함이 준 당연함 속에 우리 사랑은 야윈 달처럼 희미해져', answer: '재연' },
    { chosung: 'ㅍㄹㅈ', hint: '내 맘 Baby 비추어 비춰줘 Baby', answer: '프리즘' },
    { chosung: 'ㅇ ㅇㅂ ㅇ', hint: '오직 하나 틀림 없이 나의 답인 너', answer: '원 오브 원' },
    { chosung: 'ㅍ ㄱ', hint: '서로를 몰랐던 시간을 넘어 세상 가장 가까이 다가와 줄래', answer: '필 굳' },
    { chosung: 'ㅌㅁㅇㅅ', hint: '오늘 어두운 밤 하늘 위로 구름 이 별을 가리고 막지 못할 이 비도 내리고', answer: '투명우산' },
    { chosung: 'ㄹㅅㅌ', hint: 'I want your Lipstick 너란 Color', answer: '립스틱' },
    { chosung: 'ㄷㅌ ㅅㅌ', hint: '두 눈을 감아 꽉 감아 Oh baby', answer: '돈트 스탑' },
    { chosung: 'ㅅㅍㅌ', hint: 'It’s like a SHIFT in you and I 느끼는 건 똑같은 걸 둘이어서', answer: '쉬프트' },
    { chosung: 'ㅇ ㄴㄷ ㅁ', hint: '어둠이 찾아오면 U Need Me 말하지 않아도 돼 I’ll play it', answer: '유 니드 미' },
    { chosung: 'ㅅ ㅇㅁㅇㅈ', hint: '손을 들어 닿을 듯한 우리의 손끝이 오랫동안 빛을 잃지 않게', answer: '소 어메이징' },
    { chosung: 'ㅇ ㄷㅇ ㅇ ㄴㅇ', hint: '뜨거워지자 터질 것처럼 더 사랑할 수밖에 없게', answer: '올 데이 올 나잇' },
    { chosung: 'ㄷㄹㄹ ㄱ', hint: '창가의 비처럼 투명히 맺혀 빛나고 있어', answer: '데리러 가' },
    { chosung: 'ㅇㄷ ㅋㅂ', hint: '까만 그림자가 밤으로 밤으로 스며들듯이', answer: '언더 커버' },
    { chosung: 'ㅈㅍ', hint: '더 높이 높이 올라 Fly 두 발 아래는 땅 그 사이를 누비면', answer: '점프' },
    { chosung: 'ㅇㄴ', hint: '아픈 건 나뿐이야 괜찮아 보이겠지만 나는 쉽지 않아 내 맘은 장식이 아냐', answer: '안녕' },
    { chosung: 'ㅇㅇ ㅇㅇ ㅇ', hint: '눈앞에 네가 다시 다가와 그때와 다른 결말이 오길', answer: '아이 원트 유' },
    { chosung: 'ㅋㅁㅅㅌㄹ', hint: '깊이 더 빠지도록 쉬지 않고 난 계속 자극해', answer: '케미스트리' },
    { chosung: 'ㅇㄹㅌㄹ', hint: '너무도 깊고 선명한 자극 그 수치도 측정이 안 될 만큼', answer: '일레트릭' },
    { chosung: 'ㄷㄹㅇㅂ', hint: '늘 익숙한 왼쪽 길 그곳을 향했던 이유는 단 하나', answer: 'ㄷㄹㅇㅂ' },
    { chosung: 'ㄷㄱ', hint: 'Who waits for love 나를 떠난 너를 탓하진 않아', answer: '독감' },
    { chosung: 'ㄴㄱ ㄴㄱㄷ ㅁ', hint: '네가 남겨둔 예쁜 말들은 한 편의 시가 되어 노래가 되고', answer: '네가 남겨둔 말' },
    { chosung: 'ㅌㄴㅇ', hint: '여기 너의 자릴 비워 둔 Tonight tonight tonight', answer: '투나잇' },
    { chosung: 'ㄹㅌㄹ', hint: 'Retro love 익숙한 Feel 남들은 이해 못 해도 우린', answer: '레트로' },
    { chosung: 'ㅇㅇ ㅅㅇ', hint: 'I say love you Tell me everything 너의 눈물 그 안의 의미', answer: '아이 세이' },
    { chosung: 'ㄹ ㅇ ㄷㅇ', hint: '그게 참 좋아 꿈이 아닌 꿈속에서 놀아 호화로운 빛에 맘을 뺏긴 너와 나 둘만 있는 세상처럼 Run run run run', answer: '락 유 다운' },
  ];
  
  export default data;
  